name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CI_SA_KEY }}
          export_default_credentials: true

      - name: Enable Firestore Emulator
        run: >
          curl -sL https://firebase.tools | bash &&
          firebase setup:emulators:firestore &&
          firebase emulators:start --only=firestore --project=${{ secrets.GCP_PROJECT_ID }} &

      - name: Run tests
        run: mvn test